[package]
name = "hyper-router"
version = "0.0.1"
authors = ["Marcin Radoszewski <moriturius@gmail.com>"]
description = "Simple routing middleware for Hyper http library."
repository = "https://github.com/marad/hyper-router"
keywords = ["hyper", "router", "routing", "middleware"]

[[bin]]
name = "router_test"
path = "tests/main.rs"

[lib]
name = "hyper_router"
path = "src/lib.rs"

[dependencies]
hyper = "^0.6.8"
regex = "^0.1.41"
rustc-serialize = "*"
